#!/usr/bin/env bash
set -euo pipefail

# save-compact.sh — Save current session state before running /compact
# Run from within Claude Code: ! ~/.claude/context-guard/scripts/save-compact.sh
# Same as save-session.sh but the instruction is to /compact after.

readonly PROJECT_DIR="$(pwd)"
readonly OUTPUT_DIR="${PROJECT_DIR}/.context-guard"
readonly OUTPUT_FILE="${OUTPUT_DIR}/state.md"

find_transcript() {
  local encoded_path
  encoded_path=$(echo "${PROJECT_DIR}" | sed 's|/|-|g')

  local candidates=()
  for base in "${HOME}/.claude/projects" "${HOME}/.claude-dc/projects"; do
    local dir="${base}/${encoded_path}"
    if [[ -d "${dir}" ]]; then
      while IFS= read -r f; do
        candidates+=("${f}")
      done < <(find "${dir}" -maxdepth 1 -name "*.jsonl" -type f 2>/dev/null)
    fi
  done

  if [[ ${#candidates[@]} -eq 0 ]]; then
    echo ""
    return
  fi

  local newest=""
  local newest_time=0
  for f in "${candidates[@]}"; do
    local mtime
    mtime=$(stat -f %m "${f}" 2>/dev/null || stat -c %Y "${f}" 2>/dev/null || echo 0)
    if [[ "${mtime}" -gt "${newest_time}" ]]; then
      newest="${f}"
      newest_time="${mtime}"
    fi
  done
  echo "${newest}"
}

get_session_id() {
  basename "$1" .jsonl
}

extract_context() {
  local transcript_path="$1"
  python3 -c "
import json, sys

transcript_path = sys.argv[1]
user_messages = []
files_touched = set()
tool_actions = []

try:
    with open(transcript_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue

            msg_type = entry.get('type', '')

            if msg_type == 'human':
                content = entry.get('message', {}).get('content', '')
                if isinstance(content, str) and content.strip():
                    user_messages.append(content.strip()[:300])
                elif isinstance(content, list):
                    for part in content:
                        if isinstance(part, dict) and part.get('type') == 'text':
                            text = part.get('text', '').strip()
                            if text:
                                user_messages.append(text[:300])

            if msg_type == 'assistant':
                content = entry.get('message', {}).get('content', [])
                if isinstance(content, list):
                    for part in content:
                        if not isinstance(part, dict):
                            continue
                        if part.get('type') == 'tool_use':
                            tool_input = part.get('input', {})
                            tool_name = part.get('name', '')
                            fp = tool_input.get('file_path', '')
                            if fp:
                                files_touched.add(fp)
                            if tool_name in ('Edit', 'Write', 'Bash', 'MultiEdit'):
                                desc = tool_input.get('description', tool_input.get('command', tool_name))
                                tool_actions.append(f'{tool_name}: {str(desc)[:120]}')
except Exception:
    pass

parts = []

if user_messages:
    parts.append('## User Messages')
    for i, msg in enumerate(user_messages[-8:], 1):
        parts.append(f'{i}. {msg}')

if files_touched:
    parts.append('')
    parts.append('## Files Modified')
    for fp in sorted(files_touched)[-20:]:
        parts.append(f'- {fp}')

if tool_actions:
    parts.append('')
    parts.append('## Recent Actions')
    for action in tool_actions[-15:]:
        parts.append(f'- {action}')

print('\n'.join(parts) if parts else '(no context extracted)')
" "${transcript_path}"
}

# --- Main ---

echo "Context Guard — Save Before Compact"
echo "====================================="

transcript=$(find_transcript)
if [[ -z "${transcript}" ]]; then
  echo "Error: No transcript found for ${PROJECT_DIR}"
  exit 1
fi

session_id=$(get_session_id "${transcript}")
context=$(extract_context "${transcript}")
timestamp=$(date "+%Y-%m-%d %H:%M")

mkdir -p "${OUTPUT_DIR}"

cat > "${OUTPUT_FILE}" << EOF
# Session State — ${timestamp} (pre-compact)

**Session ID:** \`${session_id}\`
**Project:** ${PROJECT_DIR}
**Resume after compact:** Tell Claude to read this file

${context}

## Next Steps
_(Add what needs to be done next before compacting)_

---
_Generated by [claude-context-guard](https://github.com/sanztheo/claude-context-guard)_
EOF

echo ""
echo "State saved to: ${OUTPUT_FILE}"
echo ""
echo "Now run /compact in Claude Code."
echo "After compact, tell Claude: \"Read ${OUTPUT_FILE} to continue\""
